### ISSUE TITLE
Support custom database/config folder

### ISSUE THREAD

**Issue by narcotico-g** [Bill-Stewart/stctl#1]
I would like to save database and config files in different folder.

If I run syncthing.exe --home="D:\XXX" it works, but this parameter is not supported by stctl.

Best option it will be installer allow choose specific folder or read this parameters from external file where we can modify them.

Thanks

**Comment by Bill-Stewart** [comment]
What **stctl** needs is the ability to accept any arbitrary `syncthing.exe` command line parameters after its own parameters (`--start`, `--stop`, `-q`).

**Comment by Bill-Stewart** [comment]
Just released v0.0.3. Can you try the following:

1. Stop Syncthing
2. Replace `stctl.exe` v0.0.2 with v0.0.3
3. Add `-- --home="homedirectory"` (or whatever) to your **stctl** command line

The updated `stctl.exe` should let you specify whatever Syncthing parameters you want after the `--`.

Can you test?

**Comment by Bill-Stewart** [comment]
Just released v0.0.4 which adds `-p` to specify a process priority for `syncthing.exe` when using `--start`. Only works if the `setLowPriority` option in the Syncthing config file is set to `false`.

**Comment by arsinclair** [comment]
Why has it been almost a year and Syncthing Windows installation still ships with v0.0.2?
